version: '{branch}-0.0.{build}'
branches:
  except:
  - master
  - /release.*/
skip_tags: true
os: Visual Studio 2015
configuration:
  - Release
#  - Debug
platform:
  - x64
#  - Win32
#clone_depth: 10
before_build:
- git submodule init
- git submodule update
- nuget restore OpenApoc.sln
- curl http://s2.jonnyh.net/pub/cd_minimal.iso.xz -o data\cd.iso.xz
- 7z e data\cd.iso.xz -odata\
build:
  project: OpenApoc.sln
  verbosity: normal
after_build:
- git describe --tags > build-id
- set /p OPENAPOC_VERSION= < build-id
- set OPENAPOC_FILENAME=OpenApoc-%PLATFORM%-%OPENAPOC_VERSION%.7z
- set OPENAPOC_DEBUG_FILENAME=OpenApoc-debug-%PLATFORM%-%OPENAPOC_VERSION%.7z
- mkdir OpenApoc-%OPENAPOC_VERSION%
- echo %APPVEYOR_REPO_COMMIT% > OpenApoc-%OPENAPOC_VERSION%\git-commit
- echo %OPENAPOC_VERSION% > OpenApoc-%OPENAPOC_VERSION%\build-id
- copy bin\%PLATFORM%\%CONFIGURATION%\*.dll OpenApoc-%OPENAPOC_VERSION%\
- copy bin\%PLATFORM%\%CONFIGURATION%\OpenApoc.exe OpenApoc-%OPENAPOC_VERSION%\
- del data\cd.iso
- del data\cd.iso.xz
- xcopy /E data OpenApoc-%OPENAPOC_VERSION%\data\
- copy portable.txt OpenApoc-%OPENAPOC_VERSION%\
- copy README.md OpenApoc-%OPENAPOC_VERSION%\
- copy README_HOTKEYS.txt OpenApoc-%OPENAPOC_VERSION%\
- 7z a %OPENAPOC_FILENAME% OpenApoc-%OPENAPOC_VERSION% -mx=9 -myx=7
- copy bin\%PLATFORM%\%CONFIGURATION%\OpenApoc.pdb OpenApoc-%OPENAPOC_VERSION%\
- 7z a %OPENAPOC_DEBUG_FILENAME% OpenApoc-%OPENAPOC_VERSION%\*.pdb -mx=9 -myx=7
- appveyor PushArtifact %OPENAPOC_FILENAME%
- appveyor PushArtifact %OPENAPOC_DEBUG_FILENAME%
