cmake_minimum_required(VERSION 2.8)

option (BUILD_GL_3_0_RENDERER "Build an OpenGL 3.0 renderer backend" ON)
option (BUILD_GLES_2_0_RENDERER "Build an OpenGL|ES 2.0 renderer backend" OFF)
option (BUILD_ALLEGRO_RENDERER "Build an allegro renderer backend" OFF)

set (RENDERERS "")
set (RENDERER_SOURCES "")
set (RENDERER_LIBRARIES "")
set (RENDERER_INCLUDE_DIRS "")

if(BUILD_GL_3_0_RENDERER)
		find_package(OpenGL)
		if (NOT OPENGL_FOUND)
				message(WARNING "OpenGL not found for GL_3_0 renderer")
		else()
			if (NOT RENDERERS)
				set(RENDERERS "GL_3_0")
			else()
				set(RENDERERS "${RENDERERS}:GL_3_0")
			endif()
			list(APPEND RENDERER_SOURCES "framework/render/ogl_3_0_renderer.cpp")
			list(APPEND RENDERER_LIBRARIES ${OPENGL_gl_LIBRARY})
			list(APPEND RENDERER_INCLUDE_DIRS ${OPENGL_INCLUDE_DIR})
		endif()
endif()
if(BUILD_GLES_2_0_RENDERER)
		find_package(OpenGLESv2)
		if (NOT OPENGLESv2_FOUND)
				message(WARNING "OpenGLES|2 not found for GLES_2_0 renderer")
		else()
			if (NOT RENDERERS)
				set(RENDERERS "GLES_2_0")
			else()
				set(RENDERERS "${RENDERERS}:GLES_2_0")
			endif()
			list(APPEND RENDERER_SOURCES "framework/render/ogles_2_0_renderer.cpp")
			list(APPEND RENDERER_LIBRARIES ${OPENGLESv2_gl_LIBRARY})
			list(APPEND RENDERER_INCLUDE_DIRS ${OPENGLESv2_INCLUDE_DIR})
		endif()
endif()


if(BUILD_ALLEGRO_RENDERER)
		if (NOT RENDERERS)
			set(RENDERERS "allegro")
		else()
			set(RENDERERS "${RENDERERS}:allegro")
		endif()
		list(APPEND RENDERER_SOURCES "framework/render/allegro_renderer.cpp")
		list(APPEND FRAMEWORK_ALLEGRO_LIBS allegro)
endif()

if (NOT RENDERERS)
		message(FATAL_ERROR "No renderers specified")
endif()


message("Building renderers: ${RENDERERS}")
add_definitions("-DRENDERERS=\"${RENDERERS}\"")
