cmake_minimum_required(VERSION 2.8)

option (BUILD_SDL2_SOUNDBACKEND "Build an SDL2 audio backend" ON)
option (BUILD_NULL_SOUNDBACKEND "Build an null (non-functional) audio backend" ON)

set (SOUNDBACKENDS "")
set (SOUNDBACKEND_SOURCES "")
set (SOUNDBACKEND_LIBRARIES "")
set (SOUNDBACKEND_INCLUDES "")

if(BUILD_SDL2_SOUNDBACKEND)
		list(APPEND SOUNDBACKENDS sdl2)
		list(APPEND SOUNDBACKEND_SOURCES "framework/sound/sdlraw_backend.cpp")
		pkg_check_modules(PC_SDL2 REQUIRED sdl2>=2.0)
		if (NOT PC_SDL2_FOUND)
				message(FATAL_ERROR "sdl2 not found")
		endif()
		foreach (SDL2_LIB ${PC_SDL2_LIBRARIES})
				message("Searching for ${SDL2_LIB} in ${PC_SDL2_LIBRARY_DIRS}")
				find_library(SDL2_LIBRARY_PATH-${SDL2_LIB} ${SDL2_LIB} HINTS ${PC_SDL2_LIBRARY_DIRS})
				if (NOT SDL2_LIBRARY_PATH-${SDL2_LIB})
						message(FATAL_ERROR "sdl2 library ${SDL2_LIB} not found in ${PC_SDL2_LIBRARY_DIRS}")
				endif()
				message("Found ${SDL2_LIB} at ${SDL2_LIBRARY_PATH-${SDL2_LIB}}")
				list(APPEND FRAMEWORK_LIBRARIES ${SDL2_LIB})
				list(APPEND FRAMEWORK_INCLUDE_DIRS ${PC_SDL2_INCLUDE_DIRS})
		endforeach()
endif()

if(BUILD_NULL_SOUNDBACKEND)
		list(APPEND SOUNDBACKENDS null)
		list(APPEND SOUNDBACKEND_SOURCES "framework/sound/null_backend.cpp")
endif()

if (NOT SOUNDBACKENDS)
		message(FATAL_ERROR "No sound backends specified")
endif()

message("Building sound backends: ${SOUNDBACKENDS}")
