#pragma once
#include "framework/configfile.h"
#include "framework/framework.h"
#include "framework/logger.h"
#include "framework/renderer.h"
#include "framework/sound.h"
#include "game/state/stateobject.h"
#include "game/state/tilemap/tilemap.h"
#include "library/sp.h"
#include "library/strings.h"
#include "library/strings_format.h"
#include "library/vec.h"
#include <algorithm>
#include <glm/glm.hpp>
#include <glm/gtx/vector_angle.hpp>
#include <list>
#include <map>
#include <set>
#include <vector>