# project name, and type
PROJECT(OpenApoc_Dependencies C CXX)

# hide dependency warnings
add_compile_options("-w")

set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package (Threads REQUIRED)

set(USE_SYSTEM_PHYSFS OFF CACHE BOOL "Use preinstalled physfs")

find_package(PhysFS)
if(NOT USE_SYSTEM_PHYSFS)
	# Only enable the subset of physfs we actually use

	set(PHYSFS_ARCHIVE_7Z OFF CACHE BOOL "")
	set(PHYSFS_ARCHIVE_GRP OFF CACHE BOOL "")
	set(PHYSFS_ARCHIVE_HOG OFF CACHE BOOL "")
	set(PHYSFS_ARCHIVE_MVL OFF CACHE BOOL "")
	set(PHYSFS_ARCHIVE_QPAK OFF CACHE BOOL "")
	set(PHYSFS_ARCHIVE_SLB OFF CACHE BOOL "")
	set(PHYSFS_ARCHIVE_WAD OFF CACHE BOOL "")
	set(PHYSFS_ARCHIVE_ISO9660 ON CACHE BOOL "")
	set(PHYSFS_ARCHIVE_ISO9660_LOWERCASE ON CACHE BOOL "")
	set(PHYSFS_ARCHIVE_ISO9660_OPENAPOC_WORKAROUND ON CACHE BOOL "")
	set(PHYSFS_ARCHIVE_ZIP ON CACHE BOOL "")

	set(PHYSFS_BUILD_SHARED OFF CACHE BOOL "")
	set(PHYSFS_BUILD_STATIC ON CACHE BOOL "")

	set(PHYSFS_BUILD_TEST OFF CACHE BOOL "")

	add_subdirectory(physfs)
endif()
