#pragma once

#include "dependencies/pugixml/src/pugixml.hpp"
#include "forms/control.h"
#include "framework/apocresources/apocfont.h"
#include "framework/configfile.h"
#include "framework/data.h"
#include "framework/event.h"
#include "framework/font.h"
#include "framework/framework.h"
#include "framework/image.h"
#include "framework/keycodes.h"
#include "framework/logger.h"
#include "framework/renderer.h"
#include "framework/sound.h"
#include "framework/trace.h"
#include "library/colour.h"
#include "library/sp.h"
#include "library/strings.h"
#include "library/strings_format.h"
#include "library/vec.h"
#include <functional>
#include <list>
#include <map>
#include <queue>
#include <stdexcept>
