#pragma once

#include "forms/checkbox.h"
#include "forms/control.h"
#include "forms/form.h"
#include "forms/forms_enums.h"
#include "forms/graphic.h"
#include "forms/graphicbutton.h"
#include "forms/label.h"
#include "forms/listbox.h"
#include "forms/multilistbox.h"
#include "forms/radiobutton.h"
#include "forms/scrollbar.h"
#include "forms/textbutton.h"
#include "forms/textedit.h"
#include "forms/ticker.h"
#include "forms/tristatebox.h"
