name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  VCPKG_SHA: 30ef65cad98f08e7197c9a1656fbd871bcb72f2d
  VCPKG_ROOT: ${{ github.workspace }}/../vcpkg

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Download minimal cd image
      run: wget http://s2.jonnyh.net/pub/cd_minimal.iso.xz -O $GITHUB_WORKSPACE/data/cd.iso.xz

    - name: Extract minimal cd image
      run: xz -d $GITHUB_WORKSPACE/data/cd.iso.xz

    - name: Update apt-get repo
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install libsdl2-dev cmake build-essential git libunwind8-dev libboost-locale-dev libboost-filesystem-dev libboost-program-options-dev qt6-base-dev libvorbis-dev ninja-build libx11-dev libxft-dev libxext-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev

    - name: Install gcc-15
      run: sudo apt install gcc-15 g++-15

    - name: GCC 15 version check
      run: echo "GCC-15:"; which gcc-15;gcc-15 --version;

    - name: Checkout vcpkg
      shell: bash
      run: |
        git clone --no-checkout https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
        git -C $VCPKG_ROOT checkout $VCPKG_SHA

    - name: Bootstrap vcpkg
      shell: bash
      run: $VCPKG_ROOT/bootstrap-vcpkg.sh -disableMetrics

    - name: Cache vcpkg binary cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/vcpkg/archives
        key: vcpkg-bincache-${{ runner.os }}-${{ env.VCPKG_SHA }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          vcpkg-bincache-${{ runner.os }}-${{ env.VCPKG_SHA }}-

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: CC=gcc-15 CXX=g++-15 cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -GNinja -DUSE_PCH=ON -DUSE_SYSTEM_QT=ON -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
